# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'offline'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch


resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 50
sample_every_val: 4
val_check_interval: null
samples_to_generate: 10       # We advise to set it to 2 x batch_size maximum
samples_to_save: 10
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 50000
final_model_samples_to_save: 50
final_model_chains_to_save: 10

evaluate_all_checkpoints: False

# @package _global_
#general:
#    name : 'enron'
#    gpus : 1
#    wandb: 'online'
#    resume: null            # If resume, path to ckpt file from outputs directory in main directory
#    test_only: null
#    check_val_every_n_epochs: 100
#    sample_every_val: 5
#    samples_to_generate: 10
#    samples_to_save: 9
#    chains_to_save: 1
#    final_model_samples_to_generate: 36000
#    final_model_samples_to_save: 30
#    final_model_chains_to_save: 20
#train:
#    n_epochs: 750
#    batch_size: 32
#    save_model: True
#model:
#    diffusion_steps: 500
#    n_layers: 8
#    lambda_train: [5, 0]
#    extra_features: 'all'
#
#    # Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
#    # At the moment (03/08), y contains quite little information
#    hidden_mlp_dims: { 'X': 64, 'E': 32, 'y': 64 }
#
#    # The dimensions should satisfy dx % n_head == 0
#    hidden_dims: { 'dx': 128, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 128, 'dim_ffE': 64, 'dim_ffy': 128 }