name: 'Cora'
directed: True
edge_count: 10556
batch_size: 16
# graphs_gen_count: 10  # comment out to generate 1 by default 
sampling_threads: 8
sampling_method: 'ego' # ego, random_walk, uniform, mix